PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX crg: <http://www.semanticweb.org/uab/catalan-research-groups#>

# CQ01: Retrieve all sub-organizations under ResearchOrganization
SELECT DISTINCT ?subClass ?comment
WHERE {
  ?subClass rdfs:subClassOf+ crg:ResearchOrganization .
  OPTIONAL { ?subClass rdfs:comment ?comment }
}
ORDER BY ?subClass
